cart/urls.py
from django.urls import path
app_name = 'cart'

from .import views

urlpatterns=[
    path('', views.cart, name='cart'),
    path('add/<uuid:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('update-cart/<uuid:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_menu_cart', views.hx_menu_cart, name='hx_menu_cart'),
    path('hx_cart_total', views.hx_cart_total, name='hx_cart_total'),
    path('checkout/success/', views.payment_success, name='payment_sucess'),
    path('checkout/cancel/', views.payment_cancel, name="payment_cancel"),
]

shopwize/urls.py
from django.contrib import admin
from django.urls import path, include
from cart.views import add_to_cart, cart, checkout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('product/', include('products.urls')),
    path("cart/", include('cart.urls')),
    path("order/", include('order.urls')),


]

cart/models.py
from django.db import models
from helpers.models import BaseModel
from products.models import Product
from django.conf import settings

# Create your models here.
    

cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .cart import Cart
from products.models import Product
from django.conf import settings
# Create your views here.

def add_to_cart(request, product_id):
    cart = Cart(request)
    cart.add(product_id)
    return render(request, 'cart/menu_cart.html')


def cart(request):
    return render(request, 'cart/cart.html')

def update_cart(request, product_id, action):
    cart = Cart(request)

    if action == 'increment':
        cart.add(product_id, 1, True)
    else:
        cart.add(product_id, -1, True)

    product = Product.objects.get(pk=product_id)
    quantity = cart.get_item(product_id)
    
    if quantity:
        quantity = quantity['quantity']

        item = {
            'product':{
                'id':product.id,
                'name':product.name,
                'get_product_image':product.get_product_image,
                'price':product.price,
            },
            'total_price': quantity * product.price,
            'quantity':quantity
        }
    else:
        item = None

    response = render(request, 'cart/partial/cart_item.html', {'item':item})
    response['HX-Trigger'] = 'update-menu-cart'

    return response


@login_required
def checkout(request):
    pub_key = settings.STRIPE_API_KEY_PUBLISHABLE
    return render(request, 'cart/checkout.html', {'pub_key':pub_key})

def hx_menu_cart(request):
    print("HX-menu-cart")
    return render(request, 'cart/menu_cart.html')

def hx_cart_total(request):
    return render(request, 'cart/partial/cart_total.html')

def payment_success(request):
    return render(request, 'payments/success.html')

def payment_cancel(request):
    return render(request, 'payments/cancel.html')

templates/cart/cart.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-8">
	<div class="widget card">
		<h1 class="widget-title fs-4 card-title fw-bold text-primary">Products In Yout Cart</h1>
		<hr class="my-2">
		<div id="leftSection" class="card-body pt-0">
			{% if cart|length == 0 %}
			<div class="row  justify-content-between " id="cart-item-{{item.product.id}}">
				<div class="col-auto col-md-12">
					<div class="alert alert-info m-5 p-5" role="alert">
						<div class="text-center">
							<div><h1><b><i class="bi bi-cart-x"></i></b></h1></div>
							<div><h3><b>Your cart is empty</b></h3></div> 
						</div>
					  </div>
				</div>
			</div>
			{% else %}
				{% for item in cart %}
					{% include 'cart/partial/cart_item.html'%}
					
				{% endfor %}
			{% endif %}
		</div>
	</div>
</div>
<div class="col-md-3">
	<div class="widget card shadow">
		<h1 class="widget-title fs-4 card-title fw-bold text-primary">Summary</h1>
		<hr class="my-2">
		<div class="card-body pt-0">
			<!-- <div class="row justify-content-between">
				<div class="col-4">
					<p class="mb-1"><b>Subtotal</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-1"><b>${{ cart.get_total_cost }}</b></p>
				</div>
			</div>
			<div class="row justify-content-between">
				<div class="col">
					<p class="mb-1"><b>Shipping</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-1"><b>$0</b></p>
				</div>
			</div> -->
			<div class="row justify-content-between">
				<div class="col-4">
					<p><b>Total</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-1">
						<b	
							id="cartTotal"
							hx-get="{% url 'cart:hx_cart_total' %}"
                        	hx-trigger="update-menu-cart from:body"
                        	hx-swap="innerHTML"
						>{% include 'cart/partial/cart_total.html' %}
						</b>
					</p>
				</div>
			</div>
			<hr class="my-0">
		</div>
		<div id="summarySection" class="text-center mt-3">
			{% if cart|length == 0 %}
				<button id="checkoutButton" class="btn btn-lg btn-primary ms-auto" disabled>
					Checkout
				</button>
				<p class="mt-2 text-muted">Your cart is empty</p>
			{% else %}
				<a href="{% url 'cart:checkout' %}" class="btn btn-lg btn-primary ms-auto">
					Checkout
				</a>
			{% endif %}
		</div>		
	</div>
</div>

{% endblock content %}

templates/cart/checkout.html
{% extends 'base.html' %}
{% block content %}
<div class="col-xl-7">
    <div class="widget card mb-0">
        <h5 class="widget-title fs-5 card-title fw-bold text-primary">Shipping Details</h5>
        <hr class="my-2">
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="first-name" name="first_name"
                            value="{{request.user.first_name}}" placeholder="First Name">
                        <label for="first-name">First Name</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="last-name" name="last_name" placeholder="Last Name"
                            value="{{request.user.last_name}}">
                        <label for="last-name">Last Name</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="address" name="address" placeholder="Address">
                        <label for="address">Address</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="zipcode" name="zipcode" placeholder="Zipcode">
                        <label for="zipcode">Zipcode</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="city" name="city" placeholder="City/Place">
                        <label for="city">City/Place</label>
                    </div>
                </div>
            </div>
            <!-- <div class="text-center">
                <button type="submit" class="btn btn-lg btn-primary">Submit</button>
            </div> -->
        </div>
    </div>
    <div class="card">
        <h1 class="widget-title text-primary">Contact Details </h1>
        <hr class="my-2">
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email"
                            value="{{request.user.email}}">
                        <label for="email">email</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input type="tel" class="form-control" id="phone" name="phone" placeholder="Phone"
                            value="{{request.user.phone}}">
                        <label for="phone">Phone</label>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <h1 class="widget-title text-primary">Payment Details</h1>
        <hr class="my-2">
    </div>
</div>
<div class="col-md-4">
    <div class="widget card shadow">
        <h1 class="widget-title fs-4 card-title fw-bold text-primary">Summary</h1>
        <hr class="my-2">
        <div class="card-body pt-0">
            <div class="row justify-content-between">
                <div class="col-4">
                    <p class="mb-1"><b>Subtotal</b></p>
                </div>
                <div class="flex-sm-col col-auto">
                    <p class="mb-1"><b>${{ cart.get_total_cost }}</b></p>
                </div>
            </div>
            <div class="row justify-content-between">
                <div class="col">
                    <p class="mb-1"><b>Shipping</b></p>
                </div>
                <div class="flex-sm-col col-auto">
                    <p class="mb-1"><b>$0</b></p>
                </div>
            </div>
            <div class="row justify-content-between">
                <div class="col-4">
                    <p><b>Total</b></p>
                </div>
                <div class="flex-sm-col col-auto">
                    <p class="mb-1"><b>${{ cart.get_total_cost }}</b></p>
                </div>
            </div>
            <div class="text-danger" id="errors">
            </div>
            <div class="text-center mt-3">
                <button onclick="buy(event)" class="btn btn-lg btn-primary ms-auto">
                    Confirm Checkout
                </button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
    let el = document.querySelector('#errors')

    function validateForm(data) {
        let errors = []

        if (data.first_name === '') {
            errors.push('First name is empty')
        }

        if (data.last_name === '') {
            errors.push('Last name is empty')
        }

        if (data.email === '') {
            errors.push('Email is empty')
        }

        if (data.phone === '') {
            errors.push('Phone is empty')
        }

        if (data.address === '') {
            errors.push('Address is empty')
        }

        if (data.zipcode === '') {
            errors.push('Zipcode is empty')
        }

        if (data.place === '') {
            errors.push('Place is empty')
        }

        if (errors.length > 0) {
            let html = '<ul>';
            
            errors.forEach((error) => {
                html += '<li>' + error + '</li>';
            })

            el.innerHTML = html + '</ul>';
        } else {
            el.innerHTML = '';
        }

        return errors
    }

    function buy(event) {
        let inputs = document.querySelectorAll('input');
        let data = {}
        inputs.forEach(input => {
            data[input.name] = input.value;    
        });


        let errors = validateForm(data)

        if (errors.length) {
            console.log('Errors', errors)
        } else {
            var stripe = Stripe('{{ pub_key }}')

            fetch('/order/start_order/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                credentials: 'same-origin',
                body: JSON.stringify(data)
            })
            .then(function(response) {
                return response.json()
            })
            .then(function(session) {
                return stripe.redirectToCheckout({ sessionId: session.session.id })
            })
            .then(function(result) {
                if (result.error) {
                    alert(result.error.message)
                }
            })
            .catch(function(error) {
                console.log('Errors', error)
            })
        }
        event.preventDefault();
        return false;
    }
</script>
{% endblock %}

templates/cart/menu_cart.html
<a href="{% url 'cart:cart' %}" class="btn btn-outline-warning" id="menu-cart-button" >
    <i class="bi-cart-fill me-1"></i>
    Cart
    <span class="badge bg-danger text-white ms-1 rounded-pill">{{cart|length}}</span>
</a>