accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns=[
    path('register', views.UserCreationView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('activate/<uuid:token>', views.user_verification, name='activate'),
    path('logout', views.UserLogout.as_view(template_name='account/login.html', next_page="accounts:login"), name='logout'),
    path('email-templates/', views.email_template, name='email'),
    path('my-account/', views.my_account, name='my_account'),
]

cart/urls.py
from django.urls import path
app_name = 'cart'

from .import views

urlpatterns=[
    path('', views.cart, name='cart'),
    path('add/<uuid:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('update-cart/<uuid:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_menu_cart', views.hx_menu_cart, name='hx_menu_cart'),
    path('hx_cart_total', views.hx_cart_total, name='hx_cart_total'),
    path('checkout/success/', views.payment_success, name='payment_sucess'),
    path('checkout/cancel/', views.payment_cancel, name="payment_cancel"),
]

order/urls.py
from django.urls import path
app_name = 'order'

from .import views

urlpatterns=[
    path('start_order/', views.start_order, name='start_order'),
    path('detail/<slug:order_display_id>/', views.OrderDetailView.as_view(), name='order_details'),
]

shopwize/urls.py
from django.contrib import admin
from django.urls import path, include
from cart.views import add_to_cart, cart, checkout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('product/', include('products.urls')),
    path("cart/", include('cart.urls')),
    path("order/", include('order.urls')),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin, BaseUserManager
import uuid
# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('User Require Email Field')
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    email = models.EmailField(unique=True)
    username = models.CharField(blank=True, null=True, max_length=150)
    
    objects  = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self) -> str:
        return f'{self.email}'
    


class Profile(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    user = models.OneToOneField(User , on_delete=models.CASCADE , related_name="profile")
    is_email_verified = models.BooleanField(default=False)
    email_token = models.CharField(max_length=100 , null=True , blank=True)
    profile_image = models.ImageField(upload_to = 'profile')

accounts/forms.py
from typing import Any, Dict
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.contrib.auth.views import AuthenticationForm


class UserRegistrationForm(UserCreationForm):
    error_css_class = 'invalid-feedback'

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'username')
    
    def clean(self):
        data = self.cleaned_data
        print("Data: ", data)

        if User.objects.filter(email=data.get("email")).exists():
            self.add_error('email', f'Email {data.get("email")} already exists')

        if User.objects.filter(username=data.get("username")).exists():
            self.add_error('username', f'Username {data.get("username")} already exists')

        return super().clean()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Updating forms attributes
        for field in self.fields:
            new_data = {
                "class": 'form-control',
                "placeholder": str(field),
            }
            self.fields[str(field)].widget.attrs.update(new_data)


class UserLoginForm(AuthenticationForm):

    username = forms.EmailField(label='Email', error_messages={
                                'invalid': 'Please enter a valid email address in the format xyz@domain.com'})
    password = forms.CharField(widget=forms.PasswordInput, label='Password')

    error_css_class = 'invalid-feedback'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Updating forms attributes
        for field in self.fields:
            new_data = {
                "class": 'form-control',
            }
            self.fields[str(field)].widget.attrs.update(
                new_data
            )

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView
from .forms import UserRegistrationForm, UserLoginForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate, login
from accounts.models import Profile
from django.http import HttpResponse
from django.contrib.auth import views as auth_view
from django.contrib.messages.views import SuccessMessageMixin
from order.models import Order
from django.contrib.auth.decorators import login_required

# from django.core.exceptions import PermissionDenied


# Create your views here.

class UserCreationView(FormView):
    template_name = 'accounts/register.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        user = form.save()
        # email confirmation

        # for the reaseon of free trail of email services is over by default i have leave this parameter as true
        # this means user did'nt get any email for activation.
        # user will be already active
        user.is_active = True
        user.save()
        response =  super().form_valid(form)
        
        messages.success(
            self.request, f"Account created please login to your account!"
        )

        return response
    
    def form_invalid(self, form):
        for field, errors in form.errors.items():
            for error in errors:
                if field == 'password2':
                    messages.error(self.request, f"password: {error}")
                else:
                    messages.error(self.request, f"{field}: , {error}")

                
        # messages.error(
        #     self.request, "There are errors in the registration form. Please correct them.")
        return super().form_invalid(form)
    
    
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            messages.error(
                    self.request, f"Already registered ! "
                )
            return redirect('shop:home')
        return super().dispatch(request, *args, **kwargs)


def user_verification(request, token):
    token = token
    try:
        profile = Profile.objects.get(email_token=token)
        profile.is_email_verified = True
        profile.email_token=None
        profile.user.is_active = True
        profile.user.save()
        profile.save()
    except Exception as e:
        return HttpResponse(f"<h1>Link is expired</h1><p>Error:{str(e)}</p>")

    messages.success(
            request, f"Account verification successfully done! "
        )
    return redirect('accounts:login')


def email_template(request):
    return render(request, 'emails/email.html')


class UserLoginView(FormView):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('shop:home')

    def form_valid(self, form):
        email = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        next_url = self.request.GET.get('next')
        user = authenticate(self.request, email=email, password=password)
        if user:
            login(self.request, user)
            response =  super().form_valid(form)
            
            messages.success(
                    self.request, f"Login Successful ! "
                    f"Welcome {user.email}."
                )
            
            if next_url:
                return redirect(next_url)
            else:
                return redirect(self.success_url)
            
        else:
            # This code in not executing but i leave it if somthing breaks
            messages.warning(
                    self.request, f"Invalid Credientials ! "
                )
            return self.render_to_response(
                self.get_context_data(request=self.request, form=form))
    

    def form_invalid(self, form):
        name = 'john'
        messages.error(self.request, f"Invalid Credientials ! ")
        return self.render_to_response(
            self.get_context_data(request=self.request, form=form))
    

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            messages.error(
                    self.request, f"Already Logged in ! "
                )
            return redirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)


class UserLogout(SuccessMessageMixin, auth_view.LogoutView):
    success_message = "User logout successfully"

    def get_success_url(self):
        messages.success(
                    self.request, f"User logout!"
                )
        return reverse_lazy('accounts:login')

@login_required
def my_account(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'accounts/my_account.html', {"orders":orders})

templates/accounts/activation.html
{% extends 'auth_base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="widget card shadow-lg">
    <div class="card-body p-5">
        <h1 class="widget-title fs-4 card-title fw-bold text-primary">Sign In</h1>
        <form method="POST" class="needs-validation" novalidate="" autocomplete="off">
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{form.username}}
                <label class="mb-2 text-muted" for="{{form.username.auto_id}}">{{form.username.label}}</label>
                <div class="invalid-feedback">
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% else %}
                    Please enter a valid email address.
                    {% endif %}
                </div>
            </div>

            <div class="form-floating mb-3">
                {{form.password}}
                <label class="mb-2 text-muted" for="{{form.password.auto_id}}">{{form.password.label}}</label>
                <div class="invalid-feedback">
                    {% if form.password.errors %}
                    {% for error in form.password.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% else %}
                    Password is required.
                    {% endif %}
                </div>
            </div>

            <div class="d-flex align-items-center">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                <div class="invalid-feedback">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endif %}
            </div>

            <div class="text-center mt-3">
                <button type="submit" class="btn btn-lg btn-primary ms-auto" formnovalidate>
                    Login
                </button>
            </div>
        </form>
    </div>
    <div class="card-footer py-3 border-0">
        <div class="text-center">
            Don't have an account? 
            {% if request.GET.next %}
                <a href='{% url "accounts:register" %}?next={{ request.GET.next }}' class="text-dark">Create One</a>
            {% else %}
                <a href='{% url "accounts:register" %}' class="text-dark">Create One</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}
{% block script %}
<script type="text/javascript">
    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>
{% endblock %}

templates/accounts/login.html
{% extends 'auth_base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="widget card shadow-lg">
    <div class="card-body p-5">
        <h1 class="widget-title fs-4 card-title fw-bold text-primary">Sign In</h1>
        <form method="POST" class="needs-validation" novalidate="" autocomplete="off">
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{form.username}}
                <label class="mb-2 text-muted" for="{{form.username.auto_id}}">{{form.username.label}}</label>
                <div class="invalid-feedback">
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% else %}
                    Please enter a valid email address.
                    {% endif %}
                </div>
            </div>

            <div class="form-floating mb-3">
                {{form.password}}
                <label class="mb-2 text-muted" for="{{form.password.auto_id}}">{{form.password.label}}</label>
                <div class="invalid-feedback">
                    {% if form.password.errors %}
                    {% for error in form.password.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% else %}
                    Password is required.
                    {% endif %}
                </div>
            </div>

            <div class="d-flex align-items-center">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                <div class="invalid-feedback">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endif %}
            </div>

            <div class="text-center mt-3">
                <button type="submit" class="btn btn-lg btn-primary ms-auto" formnovalidate>
                    Login
                </button>
            </div>
        </form>
    </div>
    <div class="card-footer py-3 border-0">
        <div class="text-center">
            Don't have an account? <a href='{% url "accounts:register" %}' class="text-dark">Create One</a>
        </div>
    </div>
</div>

{% endblock %}
{% block script %}
<script type="text/javascript">
    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>
{% endblock %}

templates/accounts/my_account.html
{% extends 'base.html' %}
{% load static %}
{% block style %}<link href="{% static 'css/table.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<!-- <h1 class="widget-title fs-4 card-title fw-bold text-primary">My Account</h1> -->
<div class="col-md-3">
	<div class="widget card shadow">
		<h1 class="widget-title fs-4 card-title fw-bold text-primary">Profile</h1>
		<hr class="my-2">
		<div class="card-body pt-0">
			<div class="row justify-content-between">
				<div class="col-4">
					<p class="mb-2"><b>Name</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>{{request.user.first_name}} {{request.user.last_name}}</b></p>
				</div>
			</div>
			<div class="row justify-content-between">
				<div class="col">
					<p class="mb-2"><b>Email</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>{{request.user.email}}</b></p>
				</div>
			</div>
			<div class="row justify-content-between">
				<div class="col">
					<p class="mb-2"><b>Phone</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>XXXXXXXXXX</b></p>
				</div>
			</div>
			<hr class="my-0">
		</div>
	</div>
</div>
<div class="col-md-9">
	<div class="widget card">
		<h1 class="widget-title fs-4 card-title fw-bold text-primary">Orders</h1>
		<hr class="my-2">

		<div class="card bg-white m-b-30">
			<div class="card-body new-user">
				<div class="table-responsive">
					<table class="table table-hover">
						<thead>
							<tr>
								<th class="border-top-0">Order ID</th>
								<th class="border-top-0">Email</th>
								<th class="border-top-0">Paid</th>
								<th class="border-top-0">Paid Amount</th>
								<th class="border-top-0">Status</th>
							</tr>
						</thead>
						<tbody>
							{% for order in orders %}
							<tr>
								<td>
									<a href="{% url 'order:order_details' order.order_display_id %}">{{order.order_display_id}}</a>
								</td>
								<td>{{order.email}}</td>
								<td>{{order.paid}}</td>
								<td>
									{{order.paid_amount}}
								</td>
								<td>
									{{order.status}}
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/accounts/register.html
{% extends 'auth_base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
<div class="widget card shadow-lg">
    <div class="card-body p-5">
        <h1 class="widget-title fs-4 fw-bold mb-4 text-primary">Sign Up</h1>
        <form method="POST" class="needs-validation" novalidate="" autocomplete="off">
            {% csrf_token %}

            <div class="form-floating mb-2">
                {{form.email}}
                <label class="mb-1 text-muted" for="{{form.email.auto_id}}">{{form.email.label}}</label>
                <div class="invalid-feedback">
                    {% if form.email.errors %}
                    {% for error in form.email.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% else %}
                    Please enter a valid email address.
                    {% endif %}
                </div>
            </div>

            <div class="form-floating mb-2">
                {{form.username}}
                <label class="mb-1 text-muted" for="{{form.username.auto_id}}">{{form.username.label}}</label>
                <div class="invalid-feedback">
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% else %}
                    Username required.
                    {% endif %}
                </div>
            </div>

            <div class="form-floating mb-2">
                {{form.password1}}
                <label class="mb-1 text-muted" for="{{form.password1.auto_id}}">{{form.password1.label}}</label>
                <div class="invalid-feedback">
                    {% if form.password.errors %}
                    {% for error in form.password.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% else %}
                    Password is required.
                    {% endif %}
                </div>
            </div>

            <div class="form-floating mb-2">
                {{form.password2}}
                <label class="mb-2 text-muted" for="{{form.password2.auto_id}}">{{form.password2.label}}</label>
                <div class="invalid-feedback">
                    {% if form.password2.errors %}
                    {% for error in form.password2.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% else %}
                    Password is required.
                    {% endif %}
                </div>
            </div>

            <div class="d-flex align-items-center">
                <!-- {{form.agree}}
                <label class="form-check-label" for="{{form.agree.id_for_label}}">
                    I agree to the <a href="#">terms and conditions</a>
                </label> -->
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                <div class="invalid-feedback">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endif %}
            </div>

            <div class="text-center mt-3">
                <button type="submit" class="btn btn-lg btn-primary" formnovalidate>
                    Register
                </button>
            </div>
        </form>
    </div>
    <div class="card-footer py-3 border-0">
        <div class="text-center">
            Already have an account? <a href='{% url "accounts:login" %}' class="text-dark">Login</a>
        </div>
    </div>
</div>

<script>
    // Enable form validation
    function validatePassword() {
        var password1 = document.getElementById("id_password1").value;
        var password2 = document.getElementById("id_password2").value;
        var username = document.getElementById("id_username");


        // Username is empty
        if (username.value === "") {
            username.classList.add("is-invalid");
            username.classList.remove("is-valid");
            return false;

        } else {
            username.classList.add("is-valid");
            username.classList.remove("is-invalid");
        }

        // Validate strength of password
        var strongRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/;
        if (!strongRegex.test(password1)) {
            alert("Password must be at least 8 characters long and contain at least one lowercase letter, one uppercase letter, and one digit.");
            return false;
        }

        // Validate matching of passwords
        if (password1 !== password2) {
            alert("Passwords do not match.");
            return false;
        }

        return true;
    }

    (function () {
        'use strict';
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation');

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity() && !validatePassword()) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
    })();

</script>


{% endblock %}