accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns=[
    path('register', views.UserCreationView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('activate/<uuid:token>', views.user_verification, name='activate'),
    path('logout', views.UserLogout.as_view(template_name='account/login.html', next_page="accounts:login"), name='logout'),
    path('email-templates/', views.email_template, name='email'),
    path('my-account/', views.my_account, name='my_account'),
]

cart/urls.py
from django.urls import path
app_name = 'cart'

from .import views

urlpatterns=[
    path('', views.cart, name='cart'),
    path('add/<uuid:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('update-cart/<uuid:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_menu_cart', views.hx_menu_cart, name='hx_menu_cart'),
    path('hx_cart_total', views.hx_cart_total, name='hx_cart_total'),
    path('checkout/success/', views.payment_success, name='payment_sucess'),
    path('checkout/cancel/', views.payment_cancel, name="payment_cancel"),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop' 
urlpatterns = [
    path('', views.home, name='home'),
    path('shop', views.shop, name='shop'),

]

shopwize/urls.py
from django.contrib import admin
from django.urls import path, include
from cart.views import add_to_cart, cart, checkout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('product/', include('products.urls')),
    path("cart/", include('cart.urls')),
    path("order/", include('order.urls')),


]

templates/alert.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error'  %}{{ "danger" }}{% else %}{{message.tags}}{% endif %}" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
{% endif %}

templates/auth_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="author" content="Muhamad Nauval Azhar">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="This is a login page template based on Bootstrap 5">
    <title>{% block title %}{% endblock %} | Shopwize </title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">
    <!-- <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script> -->
</head>

<body>
    <section class="h-100">
        <div class="container h-100 ">
            <div class="row justify-content-sm-center h-100">
                <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
                    <div class="text-center my-5">
                    {% include 'alert.html' %}
                    </div>
                    <!-- Dynamic content goes here -->
                    {% block content %}
                    {% endblock %}
                    <!-- Dynamic content end here -->
                    <div class="text-center mt-5 text-muted">
                        Shopwize
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
        
    {% block script %}
    {% endblock %}
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %} | Shopwize</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}">
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <style type="text/css">
        .skeleton-loading {
            background-color: #f0f0f0;
            animation: pulse 1.5s infinite;
        }

        @keyframes pulse {
            0% {
                opacity: 0.5;
            }

            50% {
                opacity: 0.8;
            }

            100% {
                opacity: 0.5;
            }
        }
    </style>

    {% block style %} {% endblock %}

</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'shop:home' %}">Shopwize</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'shop:shop' %}">Shop</a></li>

                    {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link btn btn-outline-success" 
                            href="{% url 'accounts:my_account' %}">My Orders</a></li>
                        <li class="nav-item"><a class="ms-3 nav-link btn btn-outline-warning"
                                href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
                <div class="d-flex">
                    <div
                        hx-get="{% url 'cart:hx_menu_cart' %}"
                        hx-trigger="update-menu-cart from:body"
                        hx-swap="innerHTML"
                    >
                        {% include 'cart/menu_cart.html' %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
    {% include 'alert.html' %}
    <!-- Section-->
    <section class="py-5">
        <div class="container-fluid mt-3">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
            <!-- End row -->
        </div>
    </section>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <h3 class="text-center text-white">Disclaimer</h3>
            <p class="m-0 text-center text-white">The shopwize project has been created solely for educational and learning purposes.</p>
            <p class="m-0 text-center text-white">It does not involve actual commercial transactions, and no real
                monetary transactions or sensitive information are processed within the application.</p>
            <p class="m-0 text-center text-white">The project serves as a safe environment for experimenting with web
                development concepts and techniques.</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/cart.js' %}"></script>
    <script src="https://unpkg.com/htmx.org@1.9.0" integrity="sha384-aOxz9UdWG0yBiyrTwPeMibmaoq07/d3a96GCbb9x60f3mOt5zwkjdbcHFnKH8qls" crossorigin="anonymous"></script>
    <script type="text/javascript">
        function imageLoaded(imgElement) {
            // Hide placeholder when the image is loaded
            const placeholder = imgElement.previousElementSibling;
            placeholder.style.display = 'none';
        }
    </script>
    {% block scripts %} {% endblock %}
</body>

</html>