accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns=[
    path('register', views.UserCreationView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('activate/<uuid:token>', views.user_verification, name='activate'),
    path('logout', views.UserLogout.as_view(template_name='account/login.html', next_page="accounts:login"), name='logout'),
    path('email-templates/', views.email_template, name='email'),
    path('my-account/', views.my_account, name='my_account'),
]

cart/urls.py
from django.urls import path
app_name = 'cart'

from .import views

urlpatterns=[
    path('', views.cart, name='cart'),
    path('add/<uuid:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('update-cart/<uuid:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_menu_cart', views.hx_menu_cart, name='hx_menu_cart'),
    path('hx_cart_total', views.hx_cart_total, name='hx_cart_total'),
    path('checkout/success/', views.payment_success, name='payment_sucess'),
    path('checkout/cancel/', views.payment_cancel, name="payment_cancel"),
]

order/urls.py
from django.urls import path
app_name = 'order'

from .import views

urlpatterns=[
    path('start_order/', views.start_order, name='start_order'),
    path('detail/<slug:order_display_id>/', views.OrderDetailView.as_view(), name='order_details'),
]

products/urls.py
from django.urls import path
app_name = 'products'

from .import views

urlpatterns=[
    path('details/<slug:slug>', views.ProductDetailView.as_view(), name='details'),
]

shopwize/urls.py
from django.contrib import admin
from django.urls import path, include
from cart.views import add_to_cart, cart, checkout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('product/', include('products.urls')),
    path("cart/", include('cart.urls')),
    path("order/", include('order.urls')),


]

order/models.py
import random
import time
from django.db import models
from helpers.models import BaseModel
from django.conf import settings
from products.models import Product
# Create your models here.

class Order(BaseModel):

    ORDERED = 'ordered'
    SHIPPED = 'shipped'

    STATUS_CHOICES = (
        (ORDERED, 'Ordered'),
        (SHIPPED, 'Shipped')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)
    address = models.TextField()
    zipcode = models.CharField(max_length=255)
    place = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    paid = models.BooleanField(default=False)
    paid_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=ORDERED)
    order_display_id = models.CharField(max_length=20, unique=True, null=True)

    class Meta:
        db_table = 'orders'
        ordering = ("-created_at",)
    
    def save(self, *args, **kwargs):
        if not self.order_display_id:
            timestamp = str(int(time.time()))
            rand_num = str(random.randint(100000, 999999))
            self.order_display_id = timestamp + rand_num
        super().save(*args, **kwargs)


class OrderItem(BaseModel):
    order = models.ForeignKey(Order, on_delete=models.DO_NOTHING, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        db_table = 'order_items'

order/views.py
import json
import stripe

from django.http import JsonResponse
from django.conf import settings
from django.views.generic import DetailView

from cart.cart import Cart
from .models import Order, OrderItem


class OrderDetailView(DetailView):
    model = Order
    template_name = 'order/order_details.html'
    context_object_name = 'order'
    slug_field = 'order_display_id'
    slug_url_kwarg = 'order_display_id'


def start_order(request):
    print('# Initialize cart object')
    cart = Cart(request)
    data = json.loads(request.body)
    total_price = 0

    items = []

    for item in cart:
        product = item['product']
        total_price += product.price * int(item['quantity'])
        # in stripe payment 199 is 19900 
        stripe_price = int(product.price)
        stripe_price = str(stripe_price)+"00"
        
        items.append({
            'price_data':{
                'currency':'usd',
                'product_data':{
                    'name':product.name
                },
                'unit_amount':int(stripe_price)
            },
            'quantity':item['quantity']
        })
    
    # initailize stripe"
    stripe.api_key = settings.STRIPE_API_KEY_HIDDEN

    # Initialize checkout session"
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=items,
        mode='payment',
        success_url = 'http://127.0.0.1:8000/cart/checkout/success',
        cancel_url='http://127.0.0.1:8000/cart/checkout/cancel/'        
    )
    
    # creating payment intent"
    payment_intent = session.payment_intent    
    
    order_data = {
        'user': request.user,
        'first_name': data.get('first_name'),
        'last_name': data.get('last_name'),
        'email': data.get('email'),
        'address': data.get('address'),
        'zipcode': data.get('zipcode'),
        'place': data.get('city'),
        'phone': data.get('phone'),
    }


    # creating order
    order = Order.objects.create(**order_data)
    order.payment_intent = payment_intent
    order.price = total_price
    order.paid_amount = total_price
    order.paid = True
    order.save()

    # creating order items:
    for item in cart:
        product = item['product']
        item_dict = {
            'order': order,
            'product': product,
            'price': product.price * int(item['quantity']),
            'quantity': int(item['quantity'])
        }

        item = OrderItem.objects.create(**item_dict)
    
    # Clearing cart 
    cart.clear()

    # return session id to checkout page
    return JsonResponse(
        {'session':session, 'order':payment_intent}
    )

templates/order/order_details.html
{% extends 'base.html' %}
{% load static %}
{% block style %}<link href="{% static 'css/table.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<!-- <h1 class="widget-title fs-4 card-title fw-bold text-primary">My Account</h1> -->
<div class="col-md-3">
	<div class="widget card shadow">
		<h1 class="widget-title fs-4 card-title fw-bold text-primary">Order Details</h1>
		<hr class="my-2">
		<div class="card-body pt-0">
			<div class="row justify-content-between">
				<div class="col-4">
					<p class="mb-2"><b>Name</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>{{order.first_name}} {{order.user.last_name}}</b></p>
				</div>
			</div>
			<div class="row justify-content-between">
				<div class="col">
					<p class="mb-2"><b>Email</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>{{order.email}}</b></p>
				</div>
			</div>
			<div class="row justify-content-between">
				<div class="col">
					<p class="mb-2"><b>Phone</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>{{order.phone}}</b></p>
				</div>
			</div>
            <div class="row justify-content-between">
				<div class="col">
					<p class="mb-2"><b>Order Price</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>{{order.price}}</b></p>
				</div>
			</div>
            <div class="row justify-content-between">
				<div class="col">
					<p class="mb-2"><b>Paid</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>{{order.paid}}</b></p>
				</div>
			</div>
            <div class="row justify-content-between">
				<div class="col">
					<p class="mb-2"><b>Paid Amount</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>{{order.paid_amount}}</b></p>
				</div>
			</div>
            <div class="row justify-content-between">
				<div class="col">
					<p class="mb-2"><b>Order Status</b></p>
				</div>
				<div class="flex-sm-col col-auto">
					<p class="mb-2"><b>{{order.status}}</b></p>
				</div>
			</div>
			<hr class="my-0">
		</div>
	</div>
</div>
<div class="col-md-9">
	<div class="widget card">
		<h1 class="widget-title text-primary my-0">Order Items</h1>

		<div class="card bg-white">
			<div class="card-body new-user">
				<div class="table-responsive">
					<table class="table table-hover">
						<thead>
							<tr>
								<th class="border-top-0"><a class="btn btn-outline-primary" href="{% url 'accounts:my_account' %}">Back To Profile</a></th>
								<!-- <th class="border-top-0">Item</th> -->
								<th class="border-top-0">Quantity</th>
								<th class="border-top-0">Price</th>
								<!-- <th class="border-top-0">Status</th> -->
							</tr>
						</thead>
						<tbody>
							{% for item in order.items.all %}
							<tr>
								<th scope="row">
                                    <div class="media align-items-center">
                                      <a href="{% url 'products:details' item.product_id %}" class="avatar rounded-circle mr-3">
                                        <img alt="{{item.product.name}}" src="{{item.product.get_product_image}}">
                                      </a>
                                      <div class="media-body">
                                        <span class="mb-0 ms-2 text-sm">{{item.product.name}}</span>
                                      </div>
                                    </div>
                                  </th>
								<td>{{item.quantity}}</td>
								<td>
									{{item.price}}
								</td>
								
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}